export enum order {
    ascending = 1,
    descending = 0,
}

export enum currency {
    AED = 'AED',
    ARS = 'ARS',
    AUD = 'AUD',
    BDT = 'BDT',
    BHD = 'BHD',
    BRL = 'BRL',
    BTC = 'BTC',
    CAD = 'CAD',
    CHF = 'CHF',
    CLP = 'CLP',
    CNY = 'CNY',
    COP = 'COP',
    CZK = 'CZK',
    DKK = 'DKK',
    EGP = 'EGP',
    ETH = 'ETH',
    EUR = 'EUR',
    GBP = 'GBP',
    HKD = 'HKD',
    HUF = 'HUF',
    IDR = 'IDR',
    ILS = 'ILS',
    INR = 'INR',
    ISK = 'ISK',
    JPY = 'JPY',
    KES = 'KES',
    KRW = 'KRW',
    KWD = 'KWD',
    LKR = 'LKR',
    MAD = 'MAD',
    MXN = 'MXN',
    MYR = 'MYR',
    NGN = 'NGN',
    NOK = 'NOK',
    NONE = 'NONE',
    NZD = 'NZD',
    PEN = 'PEN',
    PHP = 'PHP',
    PKR = 'PKR',
    PLN = 'PLN',
    QAR = 'QAR',
    RON = 'RON',
    RSD = 'RSD',
    RUB = 'RUB',
    SAR = 'SAR',
    SEK = 'SEK',
    SGD = 'SGD',
    THB = 'THB',
    TND = 'TND',
    TRY = 'TRY',
    TWD = 'TWD',
    USD = 'USD',
    USDT = 'USDT',
    VES = 'VES',
    VND = 'VND',
    ZAR = 'ZAR',
}

export enum dayofweek {
    sunday = 1,
    monday = 2,
    tuesday = 3,
    wednesday = 4,
    thursday = 5,
    friday = 6,
    saturday = 7,
}

export enum display {
    all = 'all',
    data_window = 'data_window',
    none = 'none',
    pane = 'pane',
    price_scale = 'price_scale',
    status_line = 'status_line',
}

const types = {
    order,
    currency,
    dayofweek,
    display,
};

export default types;
